# Generated by Django 4.1 on 2022-09-18 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Saloon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('gstin', models.CharField(max_length=15)),
                ('pan_no', models.CharField(max_length=10, unique=True)),
                ('address', models.CharField(max_length=300)),
                ('no_of_sheets', models.IntegerField(default=0)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saloons', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1', 'Haircut'), ('2', 'Shaving'), ('3', 'Hair Wax')], max_length=50)),
                ('time', models.IntegerField()),
                ('price', models.IntegerField()),
                ('saloon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='registration.saloon')),
            ],
        ),
        migrations.CreateModel(
            name='Schdule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_days', models.CharField(choices=[('1', 'Haircut'), ('2', 'Shaving'), ('3', 'Hair Wax')], max_length=70)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('saloon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schdules', to='registration.saloon')),
            ],
        ),
    ]
