# Generated by Django 4.1 on 2022-09-18 18:47

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schdule',
            name='working_days',
            field=jsonfield.fields.JSONField(),
        ),
    ]
